---
- name: fail2ban is installed
  apt:
    name: fail2ban
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: "Ensure file  exists"
  stat:
    path: "/etc/yum.repos.d/sonar.repo"
  register: sonar_repo_stat

- block:
  - name: "Download SonarQube repo into '/etc/yum.repos.d/sonar.repo'"
    get_url:
      #url: " http://downloads.sourceforge.net/project/sonar-pkg/rpm/sonar.repo"
      url: " http://bla.blub"
      dest: "/etc/yum.repos.d/sonar.repo"
    retries: 5
    delay: 10
  when: not sonar_repo_stat.stat.exists
