version: 2
jobs:
  test:
    machine: true
    python:
      version: 3.6.0
    steps:
      - checkout
      - run:
          name: Install test requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run molecule tests
          command: |
            . venv/bin/activate
            molecule --debug test
