version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.7-stretch-browsers
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 18.05.0-ce
      - run:
          name: Install test requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run molecule tests
          command: |
            . venv/bin/activate
            molecule --debug test
