version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install test requirements
          command: |
            virtualenv ~/.venv
            . ~/.venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run molecule tests
          command: |
            . ~/.venv/bin/activate
            molecule --debug test
