version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run: pip install docker
      - run: pip install molecule

      - run:
          name: run tests
          command: |
            docker run --rm -i -v $(pwd):/tmp/ansible-role-fail2ban:ro -v /var/run/docker.sock:/var/run/docker.sock -w /tmp/ansible-role-fail2ban retr0h/molecule:latest sudo molecule test
