version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.7-stretch-browsers
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
          version: 17.03.0-ce
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv -f /tmp/docker/* /usr/bin
      - run:
          name: Install test requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run molecule tests
          command: |
            . venv/bin/activate
            molecule --debug test
