version: 2
jobs:
  build:
    docker:
      - image: retr0h/molecule:latest

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: run tests
          command: |
            docker run --rm -i -v $(pwd):/tmp/ansible-role-fail2ban:ro -v /var/run/docker.sock:/var/run/docker.sock -w /tmp/ansible-role-fail2ban retr0h/molecule:latest sudo molecule test

workflows:
  version: 2
    build-deploy:
      jobs:
        - build

