# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    machine: true
      - setup_remote_docker:
        docker_layer_caching: true

    working_directory: /home/circleci/ansible-role-fail2ban

    steps:
      - checkout
      - run:
          name: run tests
          command: |
            docker run --rm -i -v $(pwd):/tmp/ansible-role-fail2ban:ro -v /var/run/docker.sock:/var/run/docker.sock -w /tmp/ansible-role-fail2ban retr0h/molecule:latest sudo molecule test
