version: 2
jobs:
  build:
    docker:
      - image: retr0h/molecule:latest

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: run tests
          command: |
            molecule --debug test
