version: 2
jobs:
  build:
    working_directory: ~/ansible-role-fail2ban
    docker:
      - image: circleci/python:3.7-stretch-browsers
        environment:
          docker_host: tcp://35.237.235.193:2376
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install test requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run molecule tests
          command: |
            . venv/bin/activate
            molecule test
