version: 2
jobs:
  build:
    machine:
      enabled: true
      python:
        version: 3.6.5
    steps:
      - checkout
      - run:
          name: Install test requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run molecule tests
          command: |
            . venv/bin/activate
            molecule --debug test
