---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance-fail2ban-variables
    image: ubuntu:16.04
provisioner:
  name: ansible
  #options:
  #  vvv: true
  lint:
    name: ansible-lint
scenario:
  name: variables
verifier:
  name: testinfra
  lint:
    name: flake8
